<?php
//接口
function content_type_data_menu() {
	//定义路由
	$items['get/content_type_data'] = array(
		'title' => 'Content Type Data',
		'page callback' => 'content_type_data_func',
		'page arguments' => array(2), // 匹配通配符。
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	return $items;
}
//回到函数
function content_type_data_func($content_type){
	if(!$content_type){
		return flase;
	}
	//获取内容类型的数据ID
	$nodes = get_content_type_data($content_type);
	//初始化一个数组 用于收集数据
	$datas = array();
	foreach($nodes["node"] as $key=>$value){
		//根据获取到的数据ID获取其他字段数据
		$node = node_load($value->nid);
		//收集
		$datas[$key]["nid"] = $node->nid;
		$datas[$key]["title"] = $node->title;
	}
	//转义成JSON格式
	$json_datas = json_encode($datas);
	//返回
	return $json_datas;
}



